### ISSUE TITLE
Keine Contao 4.4 kompatibilität

### ISSUE THREAD

**Issue by MaCo7** [hypergalaktisch/contao-animate#1]
Läßt sich nicht via Contao Manager installieren. Über eine Anpassung würde mich sehr freuen.
VG, Martin

**Comment by hypergalaktisch** [comment]
Arbeite an einer Version für den Contao Manager, wird allerdings noch ein bisschen dauern.

**Comment by hypergalaktisch** [comment]
Extension ist nun kompatibel mit Contao 4.4
