### ISSUE TITLE
Fehlende JS Datei

### ISSUE THREAD

**Issue by 9teufel** [hypergalaktisch/contao-animate#5]
Habe Version 2.0.7 in Contao 4.6 installiert.

Die Console im Frontend sagt mir:
Failed to load resource: the server responded with a status of 404 (Not Found)
https://domain.de/bundles/hypergalaktischanimate/js/jquery.viewportchecker.min.js.map

**Comment by FlowinBeatz** [comment]
Da geht es nur um die .map Datei, die zum debuggen von zusammengefassten Dateien benötigt wird. Kann ignoriert werden.
